### ISSUE TITLE
IMS API: Documents with empty year result in error

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#101]
Repro Steps:
- Create a new registration (or use an existing known one) with an empty Year on the collateral
- Using the IMS-API 
-- Search for registration for the record using the serial number

Expected: The result is returned with a null year
Actual: The IMS-API returns a response with an http code of 500 (Internal Server Error) 

This issue was captured in Sentry: https://sentry.io/organizations/bc-government-registries/issues/1391900774
> **Comments:** 
> 
> 
> 
> **Type:** Bug
> **Status:** Under Review
> **Priority:** Low
> **Resolution:** 
> **Assignee:** JGUERTIN

**Comment by jguertin** [comment]
This issue has been resolved
