### ISSUE TITLE
ppr-api: create health checks endpoints

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#106]
Create the k8s readiness and liveness probes for the ppr-api.
> **Comments:** 16/Dec/19 12:02 PM;JGUERTIN;Code has been reviewed and merged
> 16/Dec/19 3:13 PM;WAMOAR;Having problems starting up, it looks like the liveness probes are causing it to be killed. I'll sort out the problem in dev and report back.
> 
> 
> **Type:** Task
> **Status:** Under Review
> **Priority:** Low
> **Resolution:** 
> **Assignee:** JGUERTIN

**Comment by jguertin** [comment]
This has been completed
