### ISSUE TITLE
Health check for EDB

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#115]
Before we get dependent on EDB, we should create a health check for it. This will give us an idea of how dependable it is.

In the ppr-api, create an endpoint that calls EDB and does a simple select. Add this endpoint to UptimeRobot for monitoring.

> **Comments:** 
> 
> 
> 
> **Type:** Task
> **Status:** Backlog
> **Priority:** Low
> **Resolution:** 
> **Assignee:**

**Comment by WalterMoar** [comment]
Completed and deployed to dev (we don't have test or production databases yet).
