### ISSUE TITLE
CI: Push docker images to a docker registry (artifactory preferable)

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#123]
To enable the CI and CD processes to exist outside of OpenShift, the build process must push its Docker images to an available registry. Currently the Github Actions are not able to push the images it creates, so we require a separate and manual process to rebuild those artifacts in OpenShift from source. This violates the CD principle of creating artifacts once for each integration.

*Acceptance Criteria:*
Given that a PR has merged into {master} in the PPR repo
When the "Build Continuous Integration Artifacts" job completes successfully
Then docker images for PPR-UI, PPR-API and IMS-API must have been pushed to Artifactory and tagged as {latest}
> **Comments:** 16/Dec/19 12:09 PM;JGUERTIN;(flag) Flag added

Blocked until Artifactory is available
> 
> 
> 
> **Type:** Task
> **Status:** Backlog
> **Priority:** High
> **Resolution:** 
> **Assignee:** JGUERTIN

**Comment by tendayichakanyuka** [comment]
@rstens can we add a dependency between this issue and the "make Artifactory available" ticket... assuming that ticket exists?

Also adding this to sprint 22. Let me know if there any issues with that.

**Comment by jguertin** [comment]
@tendayichakanyuka This is part of "automating deployment" and is targeted for Sprint 23 on our internal team board. It is currently blocked due to Artifactory being unavailable, so likely not feasible for 22.

**Comment by jguertin** [comment]
We've gone ahead for PPR API deploying building the image in GitHub Actions and pushing to `docker-registry.pathfinder.gov.bc.ca/zwmtib-tools`
