### ISSUE TITLE
Registering a Financing Statement

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#162]
As a registering party I need to be able to: 

o Register a financing statement so that I can record my interest in a piece of collateral 

* Create a draft financing statement so that I can compose a financing statement without having to submit it all at once 

* Edit a draft financing statement so that I can change a draft financing statement without having to submit or delete it 

* Delete a draft financing statement so that I can remove draft financing statement without having to submit it 

* Optionally associate the financing statement with one of my clients [folio tag] so that I can determine which client to bill 

* Optionally verify a financing statement before registering so that I can confirm that I have correctly entered the financing statementâ€™s information 

* Submit [register] a draft financing statement to the PPR Registry so that I can have the financing statement officially recognized 

* See a confirmation of financing statement registration success so that I can be assured that the registration was successful 

* See a printer-friendly confirmation of a financing statement of registration success so that I can easily print the confirmation 

* Receive a summary of my change [verification statement] in my BC Online mailbox so that I can reference the details of my registration at a later time

> **Comments:** 
> 
> 
> 
> **Type:** Story
> **Status:** Backlog
> **Priority:** Low
> **Resolution:** 
> **Assignee:**

**Comment by bryan-gilbert** [comment]
Moved all of the text above into a comment in #602
Can close this issue.
