### ISSUE TITLE
ppr-api CORS configuration

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#20]
## Background

We need to determine how to set up the Cross-Origin Resource Sharing (CORS - https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) configuration for the API.

## Details

We need to make this configurable at runtime, probably using the standard `dotenv` and `os.getenv` that we see in other BCRS apis. The configuration is currently hard-coded but we should probably go with:
 - dev: http://localhost:8080 (desktop frontend) and https://ppr-dev.pathfinder.gov.bc.ca (dev frontend).
 - test: https://ppr-test.pathfinder.gov.bc.ca (test frontend).
 - prod: https://ppr.pathfinder.gov.bc.ca (prod frontend).

This will probably all change with apigee (or other gateway) but for now it is what we know.

**Comment by WalterMoar** [comment]
This is still important, but we aren't going to be working on the Python API for the next chunk of work. Closing this.

**Comment by WalterMoar** [comment]
Re-opening this now that we're focusing on the Python API.

**Comment by bryan-gilbert** [comment]
Need to account for changing ports on localhost.  May be less of an issue once the IMS API is shutdown. Still may wish to include, by default in our code, the following for localhost
    "http://localhost:8080",
    "http://localhost:8081",
    "http://localhost:8000",
    "http://localhost:8001",
