### ISSUE TITLE
ppr-api: update search endpoint

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#222]
The original search endpoint was written to take the serial number as a parameter. This parameter should be removed, and the endpoint updated to reflect the design in https://github.com/bcgov/ppr/blob/master/ppr-api/docs/api_contract/ppr-api.v1.yaml

**Comment by jguertin** [comment]
The original `search` endpoint has been replaced with a group of endpoints at `/searches`.  This task is essentially done except removal of the old endpoint, though that should coincide with its removal from the UI.  I'll create a separate task for this.
