### ISSUE TITLE
Review process for cleaning up resources on OpenShift

### ISSUE THREAD

**Issue by bryan-gilbert** [bcgov/ppr-deprecated#281]
PR https://github.com/bcgov/ppr/pull/271 introduced the concept of applying a label (PPR_GROUP) to every and all resources (on the UI side) that work together.  These include; intermediate build config, build config, deploy config, config maps; services; routes; etc..   The idea is with this consistent label we can perform
```
oc -n 1rdehl-dev delete all,configmap -l pprgroup=$PPR_GROUP
oc -n zwmtib-tools delete all -l pprgroup=$PPR_GROUP
```

This task is to review this concept and accept the introduction of the ppr group label, or determine a better solution and go from there.

**Comment by WalterMoar** [comment]
Can we close this? I don't think we need to be automating this until we get to the point where we're doing PR based deploys.
