### ISSUE TITLE
Validate Search Criteria - Document Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#312]
As a searcher I want to validate the _Document Registration Number_ I have typed in so I can avoid potentially wasting money on an incorrect search.

**NOTE**: A valid search number is defined as "any combination of letters, characters, and numbers (up to seven characters)" @bfbowles to confirm...

**Acceptance Criteria**:
**Given** that a searcher has entered a _Document Registration Number_ value
**Then**:
- The searcher gets a visible warning when they have entered an invalid _Document Registration Number_?
- The searcher gets a visible confirmation of validity when they have entered a valid value (not to be confused with search validity)
- The searcher is allowed to dismiss the warning and still carry on with the search if they choose

**Comment by bfbowles** [comment]
The current registration number is seven characters.   Six numbers ending with a letter. Base Reg. #: 253719I
If memory serves me correctly it was seven numbers then when it maxed out the last character was changed to a letter starting at A.   Currently there is no edit on the registration number field in the search transaction.  We take their money right or wrong.

Going forward I would think on day one of offering registration through the new application we may want to start the registration number as a eight character number.   If we don’t go big bang and registrations or changes are happening in both worlds this would help to identify old from new.

The spreadsheet contains data from last week Monday to Friday.  Number of searches by type and who did them by business type.

**Comment by tendayichakanyuka** [comment]
@bfbowles have a look at the acceptance criteria as I have recently updated them... and let me know what your thoughts are on that approach.

Also @jguertin what are your thoughts on @bfbowles suggesting that we launch with an 8-character number vs a 7-character... should we be making any design decisions right now in anticipation of this?

**Comment by jguertin** [comment]
@tendayichakanyuka From my side, I've got no worries about making 8 digits acceptable, it's a pretty easy adaptation.

**Comment by bryan-gilbert** [comment]
For clarity, and for the current search theme, the UI will warn the user if they enter anything other than 1 to 8 letters and numbers.  This is not a blocking validation.
@tendayichakanyuka @jguertin @bfbowles @LaxLogic @WalterMoar 
In a later time when we work with the registration theme then the discussion here suggests the new PPR will require/force 8 character registration numbers.

**Comment by bryan-gilbert** [comment]
See PR #379 for the UI portion of this issue
