### ISSUE TITLE
Match Search Results - Document Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#313]
As a "searcher" I need to search the database for any registered interests with a document registration number that is an exact match of the _Document Registration Number_ I have entered. 

**Acceptance Criteria**:
**Given** that I am an authorized searcher 
**When**:
- I enter a search input; and
- the system has validated it – as opposed to an unforgivably invalid input, e.g. "<script>....</script>" 

**Then**:
- I obtain a summary list of all the registered interests where the _Document Registration Number_ is an exact match for the value entered
- **NOTE**: This may include _____
- It is made clear to me when the search I have just run returns nil results (**NOTE**: There may be some legalese required here... @adgatey to check with Barb)

**Comment by bryan-gilbert** [comment]
PPR users can search by registration number and see the financing statement.  The implementation is purely functional at this time yet all the essential elements are present.
