### ISSUE TITLE
Review Matched Results - Document Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#314]
PLACEHOLDER STORY: Users omit this step in today's world because the _Document Registration Number_ search returns exact matches only.

**Comment by tendayichakanyuka** [comment]
@WalterMoar, @bfbowles @LaxLogic: I had a quick discussion with @jguertin, and @bryan-gilbert this afternoon, and we determined that we are going to forgo this story for _Document Registration Number_. If you all agree, could @WalterMoar please close this issues?

**Comment by WalterMoar** [comment]
This makes sense to me, but I definitely defer to the other two plus Barb.
