### ISSUE TITLE
Select Desired Matches - Document Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#315]
As a "searcher", I want any and all exact matches returned when I searched the database for the _Document Registration Number_ I entered, automatically selected for inclusion in my search results. This is so I don't have to manually choose which matches I am interested in seeing given that I am expecting exact matches only.

**Acceptance Criteria**:

- It would be nice to see some visual cue indicating that - for this search - I will not be expected to select any desired matches but that this will be done automatically
- No need to review auto-selected matches prior to displaying actual search results

**Comment by bryan-gilbert** [comment]
Question:  do we introduce a new step (page?) between the search input and search results (e.g. show the actual single document found)?   I believe some have said that PPR will skip this step for registration number search because there is only one possible match.  In other words, for the current sprint should the flow go from #214 to #316 and should this issue #315 and #314 be placed in the backlog?

**Comment by tendayichakanyuka** [comment]
@bryan-gilbert I would like to have a conversation with the devs about what's feasible. I would recommend at least having a _behind-the-scenes_ function that auto-selects the results, even though this action may be abstracted from the UI at this stage.

**Comment by tendayichakanyuka** [comment]
Okay... so, just to document my conversation with @bryan-gilbert and @jguertin, here is the flow for the Epic: #214:

1. Specify Search Criteria: #307 
2. Validate Search Criteria: #312 
3. Match Search Results: #313 
4. Review Matched Results: #314 [NOT REQUIRED FOR THIS TYPE OF SEARCH]
5. Select Desired Matches: #315
6. Display Selected Matches: #316 
7. Deliver Search Results: #317 [NOT REQUIRED FOR THIS SPRINT... APPROACH AS STRETCH GOAL]

**Comment by bryan-gilbert** [comment]
Closing this issue since the user is taken directly to see the financing statement after doing a search by registration number. There is no step in the middle that lists matches.
