### ISSUE TITLE
Display Selected Matches - Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#316]
As a "searcher" I want the registered interests that matched the _Document Registration Number_ I entered exactly, displayed so I can review the details of these registered interests.

**Acceptance Criteria**:

+ I can see the following details:
    -  The search type (i.e. _Registration Number of Document or Statement_)
    -  The search criteria that I typed in
    -  The registration type, i.e. the act or legislation under which the registration was filed
    -  The document's base registration number (**See**: #318)
    -  The date and time the document was registered (**See**: #319)
    -  The registration length and expiry date of the document. (**NOTE**: This expiry date includes the extended time registered on subsequent renewals.)
    -  The control number is the document id number used in the draft process
    -  The name and address of the registering party (if different from the secured party)
    -  The name and address of the secured party (or parties)
    -  The name, address, and birthdate (if it has been supplied) of the debtor(s)
    -  The serial number, year, make, and model of any collateral described in vehicle collateral lines
    -  A description of any general collateral.
    -  The block number for each set of data. (**NOTE**: The block number is a five-character code that identifies a set of data. For example, all of the data relating to one debtor, or to one vehicle, would have a block number assigned to it in the PPR database. In today's world, users need to provide a block number when completing a Financing Change Statement. | **See**: #320)
+ I can page forward or back through the list of results
+ I can choose how I want these results delivered, i.e. print, email, or snail mail

**Comment by bfbowles** [comment]
Current IMS record
Registration Numb: 253719I           Life:    7        CO Renewal: N
             Date: 20141027          Time:    114657        Other: N

Postgres Table
registration_number
(
    reg_number                   serial primary key,
    base_reg_number        integer NOT NULL,
    reg_date         timestamp with time zone NOT NULL DEFAULT now(),
    life                    integer NOT NULL,

**Comment by bryan-gilbert** [comment]
Can someone please revisit the acceptance criteria and blend the comment by Bob above and consider that issue #317 covers the delivery item at the bottom of the AC list.

**Comment by tendayichakanyuka** [comment]
@bryan-gilbert, happy to do so. @bfbowles can you and I have a quick chat about this?

**Comment by bryan-gilbert** [comment]
@tendayichakanyuka @LaxLogic 
Here is a proposed AC that I suggest we implement for this sprint. 

As a "searcher" I want to see the registered interests that match the Registration Number exactly as I entered it.  I wish to review the details of these registered interests.

Acceptance Criteria:

I can see the following details:
- The search type (i.e. Registration Number of Document or Statement)
- The search criteria that I typed in
- The registration type, i.e. the act or legislation under which the registration was filed
- The document's base registration number (See: #318)
- The date and time the document was registered (See: #319)
- The registration length and expiry date of the document. (NOTE: This expiry date includes the extended time registered on subsequent renewals.)
- The control number is the document id number used in the draft process
- The name and address of the registering party (if different from the secured party)
- The name and address of the secured party (or parties)
- The name, address, and birthdate (if it has been supplied) of the debtor(s)
- The serial number, year, make, and model of any collateral described in vehicle collateral lines
- A description of any general collateral.

Excluded:

The block number for each set of data. (NOTE: The block number is a five-character code that identifies a set of data. For example, all of the data relating to one debtor, or to one vehicle, would have a block number assigned to it in the PPR database. In today's world, users need to provide a block number when completing a Financing Change Statement. | See: #320)

```
To be clear the display of this data is not in the final design (pending UX research) the information will be presented in a code-like information only format.
```
