### ISSUE TITLE
Deliver Search Results - Document Registration Number

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#317]
As a "searcher" I want the results displayed at the end of my search (i.e. all selected or auto-selected matches) delivered to me using a method of my choosing. This is so I can walk away with an official export of the search results that I have just obtained.

**Acceptance Criteria**:
- I can choose the method by which I want my search results displayed between print, email, or snail mail
- The delivered search results must contain all of the the details displayed along with the search results as specified in #316 
- If a search finds nothing that is an exact match of the document registration number I have entered, the following message will appear in the delivered search results: 

> No registered liens or encumbrances have been found on file that match EXACTLY to the search criteria listed above.

**Comment by tendayichakanyuka** [comment]
@bryan-gilbert can we have a side-bar on this issue to see what makes sense in terms of a work breakdown. Feel free to invite your developer friends.

**Comment by jguertin** [comment]
@sandrajoandaniel I believe we can just close this issue.  When we did Registration Number search, that included both Base ("Statement") Registration and "Document" Registration Numbers.

There are some Acceptance Criteria on here that don't seem specific to searching, but I'm hoping they're captured independently.

**Comment by sandrajoandaniel** [comment]
Ok.
*Sandra Daniel*
Co-Founder Openfield/ Strategy & Change Designer
iPhone: (1) 778-677-1450
Email: *sandra@openfield.design*
Website: *www.openfield.design*
Learning: www.openfieldinstitute.com
