### ISSUE TITLE
Possible Number of Base Registration Records Returned for Doc Reg Num Search

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#318]
I need help determining if it is possible for the search results returned from a _Document Registration Number_ search to include more than one base registration record. 

If yes, what's the best way to display the various individual base registration records so that they are easier to differentiate. It appears that in today's world, each base registration record is separated by a row of asterisks. 

The answer to this question will impact the acceptance criteria for #316

**Comment by LivMac-Git** [comment]
In talking with barb searching by **registration number** OR **base registration number** there will **always only be one record returned.** 

While a single document can have multiple registration numbers, each registration number will always only reference one document. 

This can potentially be closed. @tendayichakanyuka

**Comment by tendayichakanyuka** [comment]
@LaxLogic go ahead and close the task, please.
