### ISSUE TITLE
Determine if Block Numbers live on in the modernized system

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#320]
I need help determining if the _Block Number_, which I understand is a mainframe construct, will live on in the modernized system... better yet, to what extent this number will live on in the modernized system. Amongst other things, the answer to this question will determine what gets displayed along with the search results.

**Comment by adgatey** [comment]
The only thing that doesn't generate a block number is general collateral. It's a key associated between an object and a record. 

For further discussion: Currently a block number could function in an auditing capacity. What needs to be determined is if block numbers need to continue to exist, or rather if the historical block numbers need to be maintained, but no new ones are generated and that auditing is captured in a different way.

**Comment by jguertin** [comment]
Does block number provide any value to end user?  What is the purpose of the block number in todays world, is it to assist users or technology?  If technology, then it's an outdated construct and can be eliminated.

**Comment by adgatey** [comment]
@jguertin This is something we should continue to validate with Barb. I suspect that this is something from the old system that we may only need to keep if it needs to be referenced for historical information. I think we're all hoping that it can go away.

**Comment by colinanderson-cgi** [comment]
NO block numbers were implemented; this card will be  part of the exemption lists for Kevin
