### ISSUE TITLE
Create Test Strategy

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#346]
Create overall approach and address:
* Test Types
* Test Workflow
* Tools
* Test Automation Strategy
* Test Data Strategy

**Comment by tendayichakanyuka** [comment]
@rstens are you budgeting for a review cycle for this strategy? I – and possibly – others could probably start review a draft in real time, if you posted one to SharePoint, for example.

**Comment by tendayichakanyuka** [comment]
Added to Sprint 22... let me know if there's an issue with this.

**Comment by rstens** [comment]
Draft is ready for consumption.
Will upload shortly to PPR repo.

Working version can be found here: https://github.com/rstens/docs
