### ISSUE TITLE
Automated functional test framework Setup

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#349]
- [x] - Be able to run local, openshift and BrowserStack
- [x] - Reporting infrastructure - Collection of results and integration with issue management system.
- [x] - Automated or efficient component version management system
- [ ] - Project sign up for BrowserStack (free) (store secrets in OpenShift)

**Comment by tendayichakanyuka** [comment]
Added to Sprint 22... let me know if this is an issue.
