### ISSUE TITLE
Populate Stakeholder Details Template

### ISSUE THREAD

**Issue by LivMac-Git** [bcgov/ppr-deprecated#357]
I have created a document which has templates to be populated with details about the various _"top users"_. 

The intent is to discover more about our top user's background and then use this information to inform our engagement plan. 

Barb and Janis will be the primaries for this document. 

Examine the webpages of the targeted companies to populate a section of this format for each: 

Company/User Name: 
Location: 
Size of Organization (people): 
Most used Functions in PPR: 
Number of Actions:
Point of contact / Contact info: 
Notes:

Within the notes section try and provide as much information as you can* (if there isn't a lot available we will make do with whatever you can find) regarding their working process and integration with PPR.

**Comment by tendayichakanyuka** [comment]
Are we going to be storing this on SharePoint?

Also, just added this to Sprint 22. Let me know if there's any issues with that.

**Comment by LivMac-Git** [comment]
https://citz.sp.gov.bc.ca/sites/SBC/REG/Projects/MVSM/_layouts/15/DocIdRedir.aspx?ID=S52QENDTEJAE-1724982671-2218

This was already on SharePoint. It should be doable in sprint 22 but will depend on team engagement. 

Janis and barb don't show up in all the Git hub users lists so I can't assign them to this as well but I had emailed them about it and they are aware.

**Comment by janisrogers** [comment]
Details such as are known have been filled in. We will continue to update as necessary as we learn more information
