### ISSUE TITLE
ppr-ui Go to market blocker - out of date TLS support 

### ISSUE THREAD

**Issue by bryan-gilbert** [bcgov/ppr-deprecated#362]
Browsers are warning us that our bcregistry.ca site (WAM) is using an out of date version of TLS and furthermore warn the version we use will no longer be supported this MARCH.

"In March of 2020, Firefox will disable support for TLS 1.0 and TLS 1.1."

To reproduce the problem
1. Open a browser and use the development tools to see the Javascript console.
2. Open one of the registry apps. 
https://dev.bcregistry.ca/cooperatives/
https://dev.bcregistry.ca/cooperatives/auth/
https://dev.bcregistry.ca/cooperatives/ppr
3. Notice the warnings

The above is shown in Firefox.  Follow the Learn More link:
https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default​

Chrome's warning is:
The connection used to load resources from https://dev.bcregistry.ca used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.

Chrome's learn more is:
https://www.chromestatus.com/feature/5654791610957824

Chrome says:
"Deprecate TLS 1.0 and 1.1, targeting removal in Chrome 81 (early 2020). During the deprecation period, sites using those protocols will show a warning in DevTools. After the deprecation period, in 2020, they will fail to connect if they have not upgraded to TLS 1.2 by then.​"

**Comment by WalterMoar** [comment]
Still waiting on the iStore to be created. However, since this is only needed in dev and test, it won't take long once WAM is working on it.

**Comment by WalterMoar** [comment]
Changes to dev and test have been approved by David McKinnon. Now waiting on iStore submission by David Roberts.

**Comment by WalterMoar** [comment]
iStore order has been submitted to WAM.

**Comment by WalterMoar** [comment]
Checked dev with SSL Labs today and we're rated as `C` due to:

- The server supports only older protocols, but not the current best TLS 1.2. Grade capped to C.
- This server accepts RC4 cipher, but only with older protocols. Grade capped to B.
- This server does not support Forward Secrecy with the reference browsers. Grade capped to B.
- This server does not support Authenticated encryption (AEAD) cipher suites. Grade capped to B.
- This server's certificate chain is incomplete. Grade capped to B.
- This server supports TLS 1.0. Grade capped to B.

**Comment by WalterMoar** [comment]
Checked dev and we are still getting the TLS 1.0 warnings. David Roberts said that he has emailed WAM today to get a status update.

**Comment by WalterMoar** [comment]
This will be in the 14:00 to 15:00 change window today (dev only? test too? TBD).

**Comment by WalterMoar** [comment]
Completed in dev and test.
