### ISSUE TITLE
Documentation repository solution

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#365]
As Tendayi, I want us to have as close to a one-document-repository-to-kill-them-all solution as possible so that we have one place for our team and stakeholders to access all our information.

Acceptance Criteria:
- solution must be blessed by government/Registries
- I don't want to have to ask for money for this solution
- solution has to align with what the other teams are using
- solution must allow us to categorize, index, etc
- solution must allow for versioning
- it would be nice for solution to allow for collaboration

**Comment by LivMac-Git** [comment]
https://citz.sp.gov.bc.ca/sites/SBC/REG/Projects/MVSM/SitePages/AssetTeam.aspx

Here is a microsite thing that Bryce made for our team in sharepoint. (maybe this helps with some of that)

**Comment by tendayichakanyuka** [comment]
@LaxLogic this is good enough. We can iterate off this.
