### ISSUE TITLE
ppr-api: Update linting to match extensions used by lear

### ISSUE THREAD

**Issue by jguertin** [bcgov/ppr-deprecated#412]
We are currently using `pylint 2.4.3`, `flake8` and the `flake8-quotes` extension for linting. Thor pointed out the other teams use the following:

# Lint and code style
autopep8
flake8
flake8-blind-except
flake8-debugger
flake8-docstrings
flake8-isort
flake8-quotes
pep8-naming
pydocstyle<4
pylint<=2.3.1

Update linting to bring the ppr-api into alignment with the other projects

**Comment by rstens** [comment]
See lear: https://github.com/bcgov/lear/blob/master/legal-api/setup.cfg

**Comment by jguertin** [comment]
PR #656 added `flake8-blind-except`, `flake8-debugger` and `pep8-naming`.

Outstanding still are:
`flake8-docstrings`
`flake8-isort`
`pydocstyle `

**Comment by jguertin** [comment]
PR #790 added `flake8-isort`.  One more change is still required to include `pydocstyle` and `flake8-docstrings`
