### ISSUE TITLE
Add Label to the PPR repo

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#423]
As per @thorwolpert 

2020/02/05 12:45 PM
We're adding the label= bcregistry to all our repos.
It should make selecting all our repos easier, not constrain team repo name choices, and have us ready for our own GH Org, when the lab is ready to support that move.

https://github.com/bcgov?q=bcregistry

**Comment by bryan-gilbert** [comment]
Task is done.
We now appear in this search
https://github.com/bcgov?utf8=%E2%9C%93&q=bcregistry&type=&language=
