### ISSUE TITLE
ppr-api: deploy secrets and configurations to production

### ISSUE THREAD

**Issue by gh2os** [bcgov/ppr-deprecated#430]
We need to take all the openshift configurations and settings in test/dev and have them deployed to production.

**Comment by WalterMoar** [comment]
The API was deployed to production two weeks ago. Are there changes to the secrets?

https://ppr-api.pathfinder.gov.bc.ca/docs

**Comment by jguertin** [comment]
> The API was deployed to production two weeks ago. Are there changes to the secrets?
> 
> https://ppr-api.pathfinder.gov.bc.ca/docs

Oh cool.  The only configuration that's changed in the last 2 weeks is the addition of a `PPR_API_AUTH_API_URL` environment variable

**Comment by WalterMoar** [comment]
I set it to `https://auth-api.pathfinder.gov.bc.ca/api/v1`.

**Comment by jguertin** [comment]
There are 2 secrets used by the deployment configuration that are not currently part of the DC file in dev.  They should be included in the DC template:

- `sentry`: keys: `DSN` and `ENVIRONMENT `
- `ppr-database`: `HOSTNAME`, `HOSTNAME_PATRONI`, `NAME`, `PASSWORD`, `PORT`, `USERNAME`

Some of these values are not necessarily secrets, but they are stored as such for convenience of having related configuration in one place.

**Comment by WalterMoar** [comment]
The secrets are already done too. Everything should be up and running, the alembic scripts ran when the first pod spun up.

**Comment by WalterMoar** [comment]
Pretty sure this is done - closing.
