### ISSUE TITLE
PPR Homepage - Beta

### ISSUE THREAD

**Issue by Bryce13Reid** [bcgov/ppr-deprecated#433]
As the A-Team we want a beta Homepage for the PPR application in the production environment that we can continuously prove/test our deployment pipeline and system integrations. 

AC
The content and appearance of the page is "market ready".

**Comment by sandrajoandaniel** [comment]
@WalterMoar I spoke with Kaine and Thor and we have full endorsement to stand this up in production. Please go ahead with the URL you have.
