### ISSUE TITLE
ppr-ui update dependencies 

### ISSUE THREAD

**Issue by bryan-gilbert** [bcgov/ppr-deprecated#435]
As a product owner
I want to know the application is using the latest packages
because these provide the latest security fixes and features
and because keeping up to date on these packages reduces long term technical debt

At the beginning of a sprint take a two hour time boxed period to update packages used.
If an update introduces a breaking change that can be fixed in this time box then proceed. Otherwise create a new GH issue and revert to the previous version.

Steps

- [x] npm update
- [x] npm audit fix

**Comment by rstens** [comment]
This is where the automated regression tests will enable to this with little impact.
The current technical environment sadly requires a lot awareness of the impact of package updates.

There are some other tools out there that could help, I believe that GitHub has some built in scanning, but we could use Snyk or similar tools as well.

**Comment by bryan-gilbert** [comment]
Because this task has not been done for two months there are substantial changes.  
Notable changes include
```
"sbc-common-components": "^2.0.41", update from 2.0.24
```
Also ran ``` npm install -g npm ``` 
New patch version of npm available! 6.13.4 → 6.13.7  Changelog: https://github.com/npm/cli/releases/tag/v6.13.7

**Comment by WalterMoar** [comment]
GitHub does indeed have some good reporting of security vulnerabilities. It does focus only on security, though. Agreed that the ideal solution is automated, but we'll always need a little time to keep on top of these. The big worry, of course is that we'll get so out of date with packages having breaking changes that it's a huge amount of work to update. We'll probably also (at least for the frontend) to lock down our package versions.

**Comment by bryan-gilbert** [comment]
After updated needed to and could remove the Data return type on all vue components.  This was required before and it was difficult to import that interface. Now it's not needed and actually produced an error after doing updates.
