### ISSUE TITLE
ppr-ui: financing statement confirmation view

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#533]
Create a view that provides the confirmation of the submission of a financing statement. It should contain the Financing Statement component in display mode. Pass the ID of the financing statement in as a route parameter, and then GET the data. (Where is the GET done? The view shouldn't itself contain networking code?)

This task should include adding the routing from the Financing Statement view. Also, the view should have some sort of navigation back to the Home screen. Routing should be done using the Vue root router, not the provide/inject mechanism.

**Comment by bryan-gilbert** [comment]
Issue #549 and this one will be done with the same PR

**Comment by bryan-gilbert** [comment]
See PR #608
