### ISSUE TITLE
Blockers involving PPR UX Study Recruitment Bulletin.

### ISSUE THREAD

**Issue by LivMac-Git** [bcgov/ppr-deprecated#556]
This is a ticket to represent all the blockers related to the PPR Bulletin. These are not "hands-off" processes and have  required constant efforts until it goes live 

- Approvals of messaging of bulletin content

- Getting bulletin live - (Bob, Ali)

          - Issues involving the color of the message

          - Issues involving the malformation of links 

                      - Links are not clickable

                      - Modernization link is too long to add, and the short link is not working

- Creating Updates to the Modernization news page

- Getting approval for updates for modernization page

**Comment by LivMac-Git** [comment]
Talking with Chris to add a clickable link below the PPR bulletin Message

We will need to create a change ticket for this action now (as well as the green text color change)

**Comment by LivMac-Git** [comment]
We are no longer able to go to Chris because he is not on the lab teams, thus we can only use lab resources to do work. 

So we need to connect with Steven Chen (?) to do this work ( adding a clickable link), and he is not available today. 

This means we no longer need to create a change ticket for this request either.

**Comment by LivMac-Git** [comment]
Steven Chen says he doesn't usually work on BC online stuff/its been a while. Suggested I should contact one of the other front end devs but if I need Steven to do it he can. 

In order to get steven to make the change:

-  I need to ask for approval on the change to the PPR page from Debbie because it affects prod

- Then I need a David McKinnon to create a ticket for the approved change from Debbie

- Create a screen shot detailing the request (See attached below)

![image](https://user-images.githubusercontent.com/12178077/75187156-579fe500-56fe-11ea-994b-3869f39481ca.png)

**Comment by LivMac-Git** [comment]
I sent Debbie an email CCing David Mckinnon making a request for the above change. 

**Debbie Is not in today so I expect this to add further delays.** 

We currently have 3 survey responses and only one that indicated they would be willing to participate in the study.

**Comment by LivMac-Git** [comment]
Unfortunately, the link was not added to all the relevant environments. It was added to 1/4 places where the bulletin is shown. (for users with all PPR privileges) There are 3 other environments that the clickable link was not added to. 

- I will try and follow up with Steven Chen to have the update made in all of them. 

- The modernization blurb is still facing approval churn, and I am working on that as well.

**Comment by janisrogers** [comment]
Spoke to Steven about the other 3 places that need to be updated. He will send me the ticket so that I can request the update. Needs to be done in test and dev first and then verified (by us) before going to prod.

**Comment by janisrogers** [comment]
Link updated on all 4 pages in test and verified

**Comment by janisrogers** [comment]
Blurb has been added to modernization page

**Comment by LivMac-Git** [comment]
@janisrogers is this clear to be moved to done now then?

**Comment by janisrogers** [comment]
yes
