### ISSUE TITLE
Create Blurb for Modernization page regarding Study

### ISSUE THREAD

**Issue by LivMac-Git** [bcgov/ppr-deprecated#578]
We will create a blurb following the tone and standards set on the modernization page. Other requirements are currently unknown. 

-  Need to get input from Debbie and Sharon

- Need final approval from Sinead

- Send to Genevive for final posting once approved and feedback incorporated. 

Need to submit for approval by EOW

**Comment by Bryce13Reid** [comment]
@sandrajoandaniel 
here's the ticket Liv was chatting about.

**Comment by LivMac-Git** [comment]
Reopened as this is not done yet.

I have now written the Blurb, and am hoping to pass it by Trish in the next hour or so for a preliminary review. (The hope being that if I incorporate her feedback early it may make the other steps in the process more seamless) 

Trish has received it and I am waiting on a comment. (if this adds to much extra time I will move forward with the above outlined process)

Here is the content so far:





>  February 27th 2020 - Call for Participants, User Study for Personal Property Registry (PPR) System Modernization
> 
> You may have seen an update to the bulletin on BC Online urging you to provide your feedback regarding current PPR and requesting your participation in a user study.  This study will help inform the future design of the new PPR system and its modernization. 
> 
> We value your feedback and want to ensure that you as a user of this system and citizen of BC have an opportunity to have your voice heard! 
> 
> Work is underway to grow PPR from a mainframe application to a modern web application. We are also creating an API to better allow those with a high volume of transactions to leverage the system. 
> 
> If you use PPR and would like to participate in the study please add your feedback and response to the survey below! 
> 
> https://www.surveymonkey.com/r/ppr-svry

**Comment by LivMac-Git** [comment]
Sent Blurb to Trish earlier and she had a lot of feedback which resulted in drastic editing. 

Rather than let it churn with another round of feedback I am going to start moving the newly edited version through to Debbie & Sharon and then Sinead.


> February 27th 2020 - Personal Property Registry wants to hear from you.
> 
> Progress continues on the Modernization Initiative and the Personal Property Registry needs your help. 
> 
> 
> We are requesting your participation in a user study. This study will help inform the future design of the new PPR system and its modernization. 
> 
> If you use PPR and would like to participate in the study and help shape the future of PPR, please add your feedback and response to this survey. < https://www.surveymonkey.com/r/ppr-svry >

**Comment by LivMac-Git** [comment]
Emailed remaining reviewers for feedback/approval
