### ISSUE TITLE
UX - Register a financing statement system flow

### ISSUE THREAD

**Issue by sandrajoandaniel** [bcgov/ppr-deprecated#598]
Document future state register a financing statement system flow based on the BRD, PPR User Guide.

Will need to start on this asap.

**Comment by LivMac-Git** [comment]
Created a future state registration flow for a Security agreement. 
https://app.flowmapp.com/share/5ea4ebeca0f0ab3fac34ddb7da4fa05f/userflow/73310/

Perhaps move to done?

**Comment by sandrajoandaniel** [comment]
Yes pls. Bravo.
*Sandra Daniel*
Co-Founder Openfield/ Strategy & Change Designer
iPhone: (1) 778-677-1450
Email: *sandra@openfield.design*
Website: *www.openfield.design*
Learning: www.openfieldinstitute.com
