### ISSUE TITLE
Improve Visual & Usability Design of Section Labels

### ISSUE THREAD

**Issue by LivMac-Git** [bcgov/ppr-deprecated#632]
**Given:** 
Potentially start with this class as a place to look but beware of broad infield label overwrites 
> v-label theme--light

Has the following issues
- The contrast on the division labels between form segments and the background is poor. 
- The Labels are equidistance between the sections they are dividing which can create confusion for the users as to which section they refer.

**Then:**

- We should **add padding to the top** of this class with the value of **1 rem**
- Adjust the **background color** to **#aec8e2**
- (optional) change just the section dividing labels to have  **font-weight: bold** but again be sure not to affect the infield float labels.

**Comment by bryan-gilbert** [comment]
As it was
![image](https://user-images.githubusercontent.com/13558676/75731073-84766e00-5ca3-11ea-9f0f-04f346c6df88.png)

As it will be
![image](https://user-images.githubusercontent.com/13558676/75731097-9821d480-5ca3-11ea-877d-e1b985a77dad.png)
