### ISSUE TITLE
Create new BaseParty component

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#642]
AC
Component that consists of PersonName -or- BusinessName.
User can indicate which they wish to use.
Functional UI
Validation is
- must select one or the other
- if PersonName then must provide first and last
- if BusinessName then must provide business name
Interactions
- When user selects one option the other is cleared and disabled

Not in scope
UX design
Address component

**Comment by LivMac-Git** [comment]
![Registered Party input (to be updated later to auto complete)](https://user-images.githubusercontent.com/12178077/76240653-d57ce980-61f0-11ea-8f36-2393920d01c7.JPG)
![First secured party input](https://user-images.githubusercontent.com/12178077/76240660-d746ad00-61f0-11ea-9859-57cfdfa6c137.JPG)
![Collapsed Secured Parties](https://user-images.githubusercontent.com/12178077/76240714-f2192180-61f0-11ea-9717-faf7ba23301f.JPG)
These screen shots detail the base party component for secured party.
