### ISSUE TITLE
Create DebtorParty component

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#644]
Consists of a new BaseParty and an optional birthdate. May need a composite model, for ease of use.

**Comment by LivMac-Git** [comment]
![image](https://user-images.githubusercontent.com/12178077/76241435-335e0100-61f2-11ea-8543-c2f15d3d64de.png)
![image](https://user-images.githubusercontent.com/12178077/76241450-3bb63c00-61f2-11ea-8ddb-115342c2d5b6.png)
![image](https://user-images.githubusercontent.com/12178077/76241461-3fe25980-61f2-11ea-9a83-8a10cbbf39c0.png)
These screenshots detail the wireframe for the debtor component. 

If possible using the vuetify component date picker (in dialog, or picker without buttons)

**Comment by bryan-gilbert** [comment]
See https://github.com/bcgov/ppr/issues/814 for this task
