### ISSUE TITLE
Create SecuredParty component

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#645]
~Consists solely of a new BaseParty,~

As discussed, perhaps this is not needed.

**Comment by LivMac-Git** [comment]
![First secured party input](https://user-images.githubusercontent.com/12178077/76241646-889a1280-61f2-11ea-8bde-ffbc315303c4.JPG)
![5+ scrollable SP and DE](https://user-images.githubusercontent.com/12178077/76241662-8df75d00-61f2-11ea-90d1-1095af5f6eeb.JPG)
![Collapsed Secured Parties](https://user-images.githubusercontent.com/12178077/76241683-951e6b00-61f2-11ea-9d31-afa6a3804c13.JPG)
![image](https://user-images.githubusercontent.com/12178077/76241786-c39c4600-61f2-11ea-8326-4b509e0f21f0.png)


These screen shots detail the proposed design of the secured party component. 

They will have two states (editable, and collapsed) 

When clicking off of a given secured party, or debtor, it will collapse the field as shown borrowing functionality from the direct list component but with styling overwrites as shown.

Clicking anywhere on the body of the collapsed entry or the edit button will activate it in an editable mode closing whatever other editable component was open. 

Clicking the 'x' icon top right will delete the entered secured party.
