### ISSUE TITLE
Create SerialCollateral component and model

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#648]

**Comment by LivMac-Git** [comment]
![Intial Serial collateral view](https://user-images.githubusercontent.com/12178077/76243786-1dead600-61f6-11ea-9bea-e0a4c052badb.JPG)
![Different Serial input styles and collapsed serial](https://user-images.githubusercontent.com/12178077/76243794-204d3000-61f6-11ea-96da-5c41e6a5c959.JPG)
![Serial Input Types dropdown](https://user-images.githubusercontent.com/12178077/76243801-24794d80-61f6-11ea-982e-7a9cdde0de9b.JPG)


These screenshots show the different states for Serial collateral. 

initially, users will only see the button to add serial collateral alongside the button to add GC and then after opening it they will see only the type dropdown. 

Once the first type is selected then the input fields will be shown to the user.

**Comment by LivMac-Git** [comment]
The Serial Collateral will also collapse and open following the same edit model as the base party components following the director list style. 

![image](https://user-images.githubusercontent.com/12178077/76245709-956e3480-61f9-11ea-8a2f-f51cc9ac957c.png)

![image](https://user-images.githubusercontent.com/12178077/76245743-a5861400-61f9-11ea-8f2d-52d4a858b476.png)
