### ISSUE TITLE
Create CollateralItems component

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#651]
Consists of SerialCollateralList and a general collateral text box.

**Comment by LivMac-Git** [comment]
The General Collateral will follow a standard expandable text input with (at the moment) no character limit (but possible wrapping to conform with expectations for printing/paper form. There will 100% be wrapping) 

Users will not be required to enter any amount of GC lines in advance. 

The other Collateral will be entered as shown in the other tickets pertaining to Serial collateral 

![General Collateral input](https://user-images.githubusercontent.com/12178077/76245956-1299a980-61fa-11ea-99fe-7e652f44bbe7.JPG)
