### ISSUE TITLE
Production first page - Login button gives error

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#678]
Now that the first page is in https://www.bcregistry.ca/cooperatives/ppr

I found that the login button is causing an error.
* It takes a long time to react
* It cannot find the page it is redirected to 
`https://bcregistry.ca/cooperatives/auth/signin/bcsc/https%3A%2F%2Fwww.bcregistry.ca%2Fcooperatives%2Fppr%2F`

I suggest, to create a version of the first page without the login button.

**Comment by WalterMoar** [comment]
The header is provided by the auth folks on the partnerships team, so we don't have much control over the button. With the proper link in place, it now redirects quicker. Note, though, that the return from auth to our app is still not working (and I don't think that is our issue).
